#if 0
TBL_MAJOR_VERSION = 2
TBL_MINOR_VERSION = 4
TBL_VERSION     = $(TBL_MAJOR_VERSION).$(TBL_MINOR_VERSION)
#endif
#define TBL_MAJOR_VERSION 2
#define TBL_MINOR_VERSION 4
#define TBL_VERSION "2.4"

